Name: Demo BDD Test with Selenium

on:
  push:
    branches:
      - main

jobs:
  run-demo-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup python3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run demo test
        run: pytest -k 'valid_login'
